#ifndef opacity_sdk_h
#define opacity_sdk_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace opacity_core {
#endif  // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern bool say_hello_world(void);

int32_t opacity_init(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace opacity_core
#endif  // __cplusplus

#endif  /* opacity_sdk_h */
