extern crate cbindgen;

use std::env;

fn generate_c_headers() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let header_path = "../generated/include/sdk.h";

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("opacity_sdk_h")
        .with_autogen_warning(
            "/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */",
        )
        .with_namespace("opacity_core")
        .with_cpp_compat(true)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(header_path);
}

fn main() {
    // Tell Cargo that if the given file changes, to rerun this build script.
    println!("cargo:rerun-if-changed=src/lib.rs");

    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();

    match target_os.as_str() {
        // Our extern "C" functions are not defined at compile time. They have to be there
        // at runtime whenever the sdk will be loaded on iOS
        // -undefined dynamic_lookup tells Rust to trust us and not fail compilation
        // "ios" => {
        // println!("cargo:rustc-link-arg=-undefined");
        // println!("cargo:rustc-link-arg=dynamic_lookup");
        // }
        "ios" => {
            // let symbols_file = concat!(
            //     env!("CARGO_MANIFEST_DIR"),
            //     "/../opacity-ios/exported_symbols.txt"
            // );
            // println!("cargo:rustc-link-arg=-Wl,-U");
            // println!(
            //     "cargo:rustc-link-arg=-Wl,-exported_symbols_list,{}",
            //     symbols_file
            // );
            let symbols_path = concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/../opacity-ios/exported_symbols.txt"
            );
            let symbols =
                std::fs::read_to_string(symbols_path).expect("Failed to read iOS exported symbols");
            for symbol in symbols.lines().filter(|s| !s.is_empty()) {
                println!("cargo:rustc-link-arg=-Wl,-U,{}", symbol.trim());
            }
        }
        "android" => {
            println!("cargo:rustc-link-arg=-Wl,--allow-shlib-undefined");
        }
        _ => {}
    }

    if std::env::var("CARGO_CFG_CLIPPY").is_err() {
        // Only run cbindgen if not running cargo clippy
        generate_c_headers();
    }
}
